<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <title>Next.js on firebirdテクテクテクブログ</title>
        <link>https://firebird-techtalktech.com/tags/next.js/</link>
        <description>Recent content in Next.js on firebirdテクテクテクブログ</description>
        <generator>Hugo -- gohugo.io</generator>
        <language>ja</language>
        <copyright>トミー</copyright>
        <lastBuildDate>Sun, 14 Sep 2025 14:54:52 +0900</lastBuildDate><atom:link href="https://firebird-techtalktech.com/tags/next.js/index.xml" rel="self" type="application/rss+xml" /><item>
        <title>📚 【Tips】Cloud Run に Next.js アプリをデプロイしたら OpenAI の Project API Key が 401 になった話と解決法</title>
        <link>https://firebird-techtalktech.com/post/tipscloud-run-%E3%81%AB-next.js-%E3%82%A2%E3%83%97%E3%83%AA%E3%82%92%E3%83%87%E3%83%97%E3%83%AD%E3%82%A4%E3%81%97%E3%81%9F%E3%82%89-openai-%E3%81%AE-project-api-key-%E3%81%8C-401-%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%9F%E8%A9%B1%E3%81%A8%E8%A7%A3%E6%B1%BA%E6%B3%95/</link>
        <pubDate>Sun, 14 Sep 2025 14:54:52 +0900</pubDate>
        
        <guid>https://firebird-techtalktech.com/post/tipscloud-run-%E3%81%AB-next.js-%E3%82%A2%E3%83%97%E3%83%AA%E3%82%92%E3%83%87%E3%83%97%E3%83%AD%E3%82%A4%E3%81%97%E3%81%9F%E3%82%89-openai-%E3%81%AE-project-api-key-%E3%81%8C-401-%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%9F%E8%A9%B1%E3%81%A8%E8%A7%A3%E6%B1%BA%E6%B3%95/</guid>
        <description>&lt;h2 id=&#34;記事概要&#34;&gt;記事概要
&lt;/h2&gt;&lt;h2 data-sourcepos=&#34;1:1-1:15&#34;&gt;
&lt;span id=&#34;はじめに&#34; class=&#34;fragment&#34;&gt;&lt;/span&gt;&lt;a href=&#34;#%E3%81%AF%E3%81%98%E3%82%81%E3%81%AB&#34;&gt;&lt;i class=&#34;fa fa-link&#34;&gt;&lt;/i&gt;&lt;/a&gt;はじめに&lt;/h2&gt;
&lt;p data-sourcepos=&#34;2:1-2:296&#34;&gt;ローカルでは問題なく動いていたNext.jsアプリを、Google CloudのCloud Runにデプロイしたところ、作成したアプリ内で実装していたOpenAIのAPI呼び出しだけが &lt;code&gt;401 Incorrect API key provided&lt;/code&gt; になってしまうという問題に遭遇しました。&lt;/p&gt;
&lt;p data-sourcepos=&#34;4:1-4:17&#34;&gt;最終的には&lt;/p&gt;
&lt;blockquote data-sourcepos=&#34;5:1-5:72&#34;&gt;
&lt;p data-sourcepos=&#34;5:3-5:72&#34;&gt;&lt;code&gt;--set-build-env-vars&lt;/code&gt; と &lt;code&gt;
&lt;hr&gt;
&lt;p&gt;&lt;strong&gt;出典&lt;/strong&gt;: &lt;a class=&#34;link&#34; href=&#34;https://qiita.com/popapipapapi/items/ab03a5dd51b186588f0d&#34;  target=&#34;_blank&#34; rel=&#34;noopener&#34;
    &gt;Qiita&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;収集日時&lt;/strong&gt;: 2025-09-14T14:54:22.607444&lt;/p&gt;
&lt;p&gt;&lt;a class=&#34;link&#34; href=&#34;https://qiita.com/popapipapapi/items/ab03a5dd51b186588f0d&#34;  target=&#34;_blank&#34; rel=&#34;noopener&#34;
    &gt;🔗 元記事を読む&lt;/a&gt;&lt;/p&gt;
</description>
        </item>
        <item>
        <title>📚 Next.js静的サイトをS3&#43;CloudFrontで公開した際のサブページ403(AccessDenied)エラー解決録</title>
        <link>https://firebird-techtalktech.com/post/next.js%E9%9D%99%E7%9A%84%E3%82%B5%E3%82%A4%E3%83%88%E3%82%92s3-cloudfront%E3%81%A7%E5%85%AC%E9%96%8B%E3%81%97%E3%81%9F%E9%9A%9B%E3%81%AE%E3%82%B5%E3%83%96%E3%83%9A%E3%83%BC%E3%82%B8403accessdenied%E3%82%A8%E3%83%A9%E3%83%BC%E8%A7%A3%E6%B1%BA%E9%8C%B2/</link>
        <pubDate>Sun, 14 Sep 2025 14:54:52 +0900</pubDate>
        
        <guid>https://firebird-techtalktech.com/post/next.js%E9%9D%99%E7%9A%84%E3%82%B5%E3%82%A4%E3%83%88%E3%82%92s3-cloudfront%E3%81%A7%E5%85%AC%E9%96%8B%E3%81%97%E3%81%9F%E9%9A%9B%E3%81%AE%E3%82%B5%E3%83%96%E3%83%9A%E3%83%BC%E3%82%B8403accessdenied%E3%82%A8%E3%83%A9%E3%83%BC%E8%A7%A3%E6%B1%BA%E9%8C%B2/</guid>
        <description>&lt;h2 id=&#34;記事概要&#34;&gt;記事概要
&lt;/h2&gt;&lt;h1 data-sourcepos=&#34;1:1-1:17&#34;&gt;
&lt;span id=&#34;1-はじめに&#34; class=&#34;fragment&#34;&gt;&lt;/span&gt;&lt;a href=&#34;#1-%E3%81%AF%E3%81%98%E3%82%81%E3%81%AB&#34;&gt;&lt;i class=&#34;fa fa-link&#34;&gt;&lt;/i&gt;&lt;/a&gt;1. はじめに&lt;/h1&gt;
&lt;p data-sourcepos=&#34;2:1-2:545&#34;&gt;Next.jsで静的エクスポート（next export）したWebサイトを、AWS S3とCloudFrontを利用して公開する構成において、特定の条件下でエラーが発生した。トップページ（/）からの画面遷移は問題なく機能するものの、サブページ（例: /news/1）のURLに直接アクセスしたり、ブラウザでリロードしたりすると、XML形式のAccessDeniedエラーが返される事象に遭遇した。本稿では、その原因と解決に至るまでの手順を記録する。&lt;/p&gt;
&lt;h1 data-sourcepos=&#34;4:1-4:20&#34;&gt;
&lt;span id=&#34;2-事象と原因&#34; class=&#34;fragment&#34;&gt;&lt;/span&gt;
&lt;hr&gt;
&lt;p&gt;&lt;strong&gt;出典&lt;/strong&gt;: &lt;a class=&#34;link&#34; href=&#34;https://qiita.com/N622/items/5453c60093fcaf8f8645&#34;  target=&#34;_blank&#34; rel=&#34;noopener&#34;
    &gt;Qiita&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;収集日時&lt;/strong&gt;: 2025-09-14T14:54:09.456956&lt;/p&gt;
&lt;p&gt;&lt;a class=&#34;link&#34; href=&#34;https://qiita.com/N622/items/5453c60093fcaf8f8645&#34;  target=&#34;_blank&#34; rel=&#34;noopener&#34;
    &gt;🔗 元記事を読む&lt;/a&gt;&lt;/p&gt;
</description>
        </item>
        
    </channel>
</rss>
