<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <title>Repos on firebirdテクテクテクブログ</title>
        <link>https://firebird-techtalktech.com/tags/repos/</link>
        <description>Recent content in Repos on firebirdテクテクテクブログ</description>
        <generator>Hugo -- gohugo.io</generator>
        <language>ja</language>
        <copyright>トミー</copyright>
        <lastBuildDate>Sun, 14 Sep 2025 14:54:52 +0900</lastBuildDate><atom:link href="https://firebird-techtalktech.com/tags/repos/index.xml" rel="self" type="application/rss+xml" /><item>
        <title>📚 プロキシ環境下におけるAzure DevOps ReposへのGit接続エラー「fatal: unable to access」の原因と対処法</title>
        <link>https://firebird-techtalktech.com/post/%E3%83%97%E3%83%AD%E3%82%AD%E3%82%B7%E7%92%B0%E5%A2%83%E4%B8%8B%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8Bazure-devops-repos%E3%81%B8%E3%81%AEgit%E6%8E%A5%E7%B6%9A%E3%82%A8%E3%83%A9%E3%83%BCfatal-unable-to-access%E3%81%AE%E5%8E%9F%E5%9B%A0%E3%81%A8%E5%AF%BE%E5%87%A6%E6%B3%95/</link>
        <pubDate>Sun, 14 Sep 2025 14:54:52 +0900</pubDate>
        
        <guid>https://firebird-techtalktech.com/post/%E3%83%97%E3%83%AD%E3%82%AD%E3%82%B7%E7%92%B0%E5%A2%83%E4%B8%8B%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8Bazure-devops-repos%E3%81%B8%E3%81%AEgit%E6%8E%A5%E7%B6%9A%E3%82%A8%E3%83%A9%E3%83%BCfatal-unable-to-access%E3%81%AE%E5%8E%9F%E5%9B%A0%E3%81%A8%E5%AF%BE%E5%87%A6%E6%B3%95/</guid>
        <description>&lt;h2 id=&#34;記事概要&#34;&gt;記事概要
&lt;/h2&gt;&lt;h2 data-sourcepos=&#34;1:1-1:15&#34;&gt;
&lt;span id=&#34;はじめに&#34; class=&#34;fragment&#34;&gt;&lt;/span&gt;&lt;a href=&#34;#%E3%81%AF%E3%81%98%E3%82%81%E3%81%AB&#34;&gt;&lt;i class=&#34;fa fa-link&#34;&gt;&lt;/i&gt;&lt;/a&gt;はじめに&lt;/h2&gt;
&lt;p data-sourcepos=&#34;2:1-2:204&#34;&gt;業務で利用するネットワーク、特にプロキシサーバーを経由する環境において、特定のツールが期待通りに動作しない問題に直面することがあります。&lt;/p&gt;
&lt;p data-sourcepos=&#34;4:1-4:296&#34;&gt;Webブラウザからは問題なくAzure DevOpsのWebポータルにアクセスできるにもかかわらず、Visual Studio Codeやコマンドラインから&lt;code&gt;git clone&lt;/code&gt;を実行しようとすると、以下のようなエラーメッセージが表示され、処理が失敗しました。&lt;/p&gt;
&lt;p data-sourcepos=&#34;6:1-6:122&#34;&gt;&lt;a href=&#34;https://qiita-user-cont
&lt;hr&gt;
&lt;p&gt;&lt;strong&gt;出典&lt;/strong&gt;: &lt;a class=&#34;link&#34; href=&#34;https://qiita.com/abachan/items/2c7be86fb4e132598192&#34;  target=&#34;_blank&#34; rel=&#34;noopener&#34;
    &gt;Qiita&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;収集日時&lt;/strong&gt;: 2025-09-14T14:54:12.628994&lt;/p&gt;
&lt;p&gt;&lt;a class=&#34;link&#34; href=&#34;https://qiita.com/abachan/items/2c7be86fb4e132598192&#34;  target=&#34;_blank&#34; rel=&#34;noopener&#34;
    &gt;🔗 元記事を読む&lt;/a&gt;&lt;/p&gt;
</description>
        </item>
        
    </channel>
</rss>
